# SmolLM1 1.7B trained on 1T tokens
checkpoints:
  checkpoint_interval: 2000
  checkpoints_path: ../checkpoints/7B_rope_v4_topk8_svd_method7_rank64
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: ../checkpoints/meta-llama/Llama-2-7b_nt
  save_final_state: true
  save_initial_state: true
  load_lr_scheduler: false
  load_optimizer: false

data_stages:
- data:
    dataset:
      dataset_folder: # paths to tokenized datasets
        - ../../../data/llama2_datasets/fineweb-edu-dedup
        - ../../../data/llama2_datasets/cosmopedia-v2
        - ../../../data/llama2_datasets/python-edu
        - ../../../data/llama2_datasets/open-web-math
        - ../../../data/llama2_datasets/stackoverflow
      dataset_weights:
        - 0.85
        - 0.15
        - 0.08
        - 0.06
        - 0.01
    num_loading_workers: 1
    seed: 42
  name: training stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: mla_smollm_ft_nt
  run: 7B_rope_v4_topk8_svd_method7_rank64
  seed: 42 # 8
  step: null
logging:
  iteration_step_info_interval: 100
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.022097086912079608
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 4096
    initializer_range: 0.02
    intermediate_size: 11008
    is_llama_config: true
    max_position_embeddings: 4096
    num_attention_heads: 32
    num_hidden_layers: 32
    num_key_value_heads: 32
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 32000
    RoPE:
      partial_rope_version: 4
      top_k_rope_dim: 8
      lask_k_rope_dim: 0
      uniform_start_point: 0
      uniform_step: 1
      qk_tensor_path: ../utils/qk_tensor_7B.pth
      n_gqa_group: 1
    SVD:
      method: 7
      low_rank: 64
optimizer:
  accumulate_grad_in_fp32: false
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0001 # 0.0005
    lr_decay_starting_step: 10000 # 400000
    lr_decay_steps: 2000 # 100000
    lr_decay_style: 1-sqrt
    lr_warmup_steps: 1000 # 2000
    lr_warmup_style: linear
    min_decay_lr: 0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 1
parallelism:
  dp: 16 # 64
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: ../checkpoints/meta-llama/Llama-2-7b-hf
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 16
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 1 # GBS = 8*4*8*sequence_length = 256*sequence_length = 0.5M tokens
  sequence_length: 4096
  train_steps: 12000 # 500000
  val_check_interval: -1
